//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApplication
{
    using System;
    using System.Collections.Generic;
    
    public partial class Account
    {
        public Account()
        {
            this.Bills = new HashSet<Bill>();
            this.BranchImportBallots = new HashSet<BranchImportBallot>();
            this.HeadquaterImportBallots = new HashSet<HeadquaterImportBallot>();
            this.ProposeBallots = new HashSet<ProposeBallot>();
        }
    
        public string AccountCode { get; set; }
        public string FullName { get; set; }
        public string Address { get; set; }
        public string Phone { get; set; }
        public string IdentityCard { get; set; }
        public string Account1 { get; set; }
        public string Password { get; set; }
        public string Authorities { get; set; }
    
        public virtual ICollection<Bill> Bills { get; set; }
        public virtual ICollection<BranchImportBallot> BranchImportBallots { get; set; }
        public virtual ICollection<HeadquaterImportBallot> HeadquaterImportBallots { get; set; }
        public virtual ICollection<ProposeBallot> ProposeBallots { get; set; }
    }
}
