//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApplication
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bill
    {
        public Bill()
        {
            this.BillDetails = new HashSet<BillDetail>();
        }
    
        public string BallotNum { get; set; }
        public System.DateTime Date { get; set; }
        public double Total { get; set; }
        public double GuestMoney { get; set; }
        public double ExcessCash { get; set; }
        public int TotalNum { get; set; }
        public int POS { get; set; }
        public string AccountCode { get; set; }
    
        public virtual Account Account { get; set; }
        public virtual ICollection<BillDetail> BillDetails { get; set; }
    }
}
