//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApplication
{
    using System;
    using System.Collections.Generic;
    
    public partial class BranchImportBallot
    {
        public string BallotNum { get; set; }
        public string HeadquaterBallotNum { get; set; }
        public System.DateTime InputDate { get; set; }
        public string Branch { get; set; }
        public string AccountCode { get; set; }
    
        public virtual Account Account { get; set; }
        public virtual HeadquaterImportBallot HeadquaterImportBallot { get; set; }
    }
}
