//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApplication
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public Product()
        {
            this.BillDetails = new HashSet<BillDetail>();
            this.BranchImportBallotDetails = new HashSet<BranchImportBallotDetail>();
            this.HeadquaterImportBallotDetails = new HashSet<HeadquaterImportBallotDetail>();
            this.PriceHistories = new HashSet<PriceHistory>();
            this.PromotionInformations = new HashSet<PromotionInformation>();
            this.ProposeBallotDetails = new HashSet<ProposeBallotDetail>();
        }
    
        public string ProductCode { get; set; }
        public string ProductName { get; set; }
        public string Image { get; set; }
        public string TypeCode { get; set; }
        public string SupplierCode { get; set; }
    
        public virtual ICollection<BillDetail> BillDetails { get; set; }
        public virtual ICollection<BranchImportBallotDetail> BranchImportBallotDetails { get; set; }
        public virtual ICollection<HeadquaterImportBallotDetail> HeadquaterImportBallotDetails { get; set; }
        public virtual ICollection<PriceHistory> PriceHistories { get; set; }
        public virtual ProductCategory ProductCategory { get; set; }
        public virtual Supplier Supplier { get; set; }
        public virtual ICollection<PromotionInformation> PromotionInformations { get; set; }
        public virtual ICollection<ProposeBallotDetail> ProposeBallotDetails { get; set; }
    }
}
