//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApplication
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProposeBallot
    {
        public ProposeBallot()
        {
            this.HeadquaterImportBallots = new HashSet<HeadquaterImportBallot>();
        }
    
        public string BallotNum { get; set; }
        public System.DateTime ProposeDate { get; set; }
        public string SupplierCode { get; set; }
        public string AccountCode { get; set; }
    
        public virtual Account Account { get; set; }
        public virtual ICollection<HeadquaterImportBallot> HeadquaterImportBallots { get; set; }
        public virtual Supplier Supplier { get; set; }
    }
}
